# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-21 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='bjp',
        ),
        migrations.AddField(
            model_name='submission',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
